version: '3.8'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: xopti_user
      POSTGRES_PASSWORD: xopti_pass
      POSTGRES_DB: xopti_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: